#
# Copyright (c) 2021, 2026 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

name: Jakarta IStack Commons

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test on JDK ${{ matrix.java_version }} 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java_version: [ 17 , 21, 25]

    steps:
    - name: Checkout for build
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java_version }}
        cache: maven
    - name: Verify
      run: |
        cd istack-commons
        mvn -B -V -U -C -Pstaging,oss-release,license-check clean install org.glassfish.copyright:glassfish-copyright-maven-plugin:check -Dgpg.skip=true -Dittest=true -Dcopyright.ignoreyear=true
#    - name: Upload license-check info
#      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
#      with:
#        name: license-summary.txt
#        path: istack-commons/target/dash/summary
