#
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

name: Jakarta IStack Commons

on:
  pull_request:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test on JDK ${{ matrix.java_version }} 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java_version: [ 11, 17 , 21-ea]

    steps:
    - name: Checkout for build
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java_version }}
        cache: maven
    - name: Verify
      run: |
        cd istack-commons
        mvn -B -V -U -C -Pstaging,oss-release,license-check clean verify org.glassfish.copyright:glassfish-copyright-maven-plugin:check -Dgpg.skip=true -Dittest=true -Dcopyright.ignoreyear=true
    - name: Upload license-check info
      uses: actions/upload-artifact@v3
      with:
        name: license-summary.txt
        path: istack-commons/target/dash/summary
